from dataclasses import dataclass, field
from typing import Dict, Any, Optional

@dataclass
class Hypothesis:
    """Represents a candidate next step (a hypothesis)."""
    id: str
    rule_id: str               # Applied rule ID (e.g., "ARITH-ADD-001")
    current_expr: str          # Expression before application
    next_expr: str             # Expression after application (prediction)
    score: float = 0.0         # Evaluation score
    metadata: Dict[str, Any] = field(default_factory=dict) # Metadata for explanation or debugging
    
    # Optional: Explanation generated by the agent
    explanation: Optional[str] = None

@dataclass
class SearchNode:
    """Represents a node in the search tree (for lookahead)."""
    expression: str
    parent: Optional['SearchNode']
    rule_applied: Optional[str]
    depth: int
    score: float
